version: '3.8'

services:
  app:
    build:
      context: .
      args:
        SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
